### ISSUE TITLE
docker run does not work anymore

### ISSUE THREAD

**Issue by freiit** [tutumcloud/unixbench#1]
Hi,

maybe that project is not longer maintained, but I followed the tutorial, build my own docker container and run it. Anything I do wrong or it the whole thing outdated?

Error response from daemon: Cannot start container d931140c61b02516e51f5e0da7d3beac328147061f1e563f78c21c20ebb0b01f: lstat /mnt/sda1/var/lib/docker/aufs/mnt/d931140c61b02516e51f5e0da7d3beac328147061f1e563f78c21c20ebb0b01f/tmp/UnixBench5.1.3.tgz/UnixBench: not a directory

**Comment by fermayo** [comment]
This has been fixed. Can you try running `docker run tutum/unixbench`?

**Comment by freiit** [comment]
Thanx. tutum/unixbench is working. :)

**Comment by fermayo** [comment]
no problem!
